"use client";

import { use } from "react";
import Link from "next/link";
import { ProjectShell } from "@/components/ProjectShell";
import { getProjectById, getEventsByProjectId } from "@/lib/mock-data";

export default function TimelinePage({ params }: { params: Promise<{ id: string }> }) {
  const { id: projectId } = use(params);
  const project = getProjectById(projectId);
  const events = getEventsByProjectId(projectId).sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  if (!project) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-100">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Project Not Found</h1>
          <p className="mt-2 text-slate-400">The project {projectId} does not exist.</p>
          <Link href="/projects" className="mt-6 inline-block rounded-xl bg-blue-600 px-4 py-2 font-medium text-white">
            Back to Projects
          </Link>
        </div>
      </div>
    );
  }

  return (
    <ProjectShell
      projectId={projectId}
      projectName={project.name}
      title="Incident Timeline"
      subtitle="Chronological sequence of security events and alerts."
      tokenUsed={project.tokenUsed}
    >
      <div className="mb-6 rounded-2xl border border-slate-800 bg-slate-900/70 p-6">
        <h2 className="text-lg font-semibold text-white">Storyline Summary</h2>
        <p className="mt-2 text-sm text-slate-400">
          This timeline tracks defensive security events, access logs, and triggered rules.
          Events marked as synthetic are generated by the lab environment to test detections.
        </p>
      </div>

      <div className="space-y-6 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-700 before:to-transparent">
        {events.length === 0 ? (
          <div className="text-center py-10 relative z-10">
            <p className="text-sm text-slate-500 bg-slate-950 px-4 py-1 inline-block rounded-full border border-slate-800">No events recorded.</p>
          </div>
        ) : (
          events.map((event, index) => (
            <div key={event.id} className={`relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active`}>
              <div className="flex items-center justify-center w-10 h-10 rounded-full border border-slate-700 bg-slate-900 shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 shadow shadow-slate-900 z-10">
                <div className={`w-3 h-3 rounded-full ${event.severity === 'High' ? 'bg-red-500' : 'bg-blue-500'}`}></div>
              </div>
              <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] rounded-2xl border border-slate-800 bg-slate-900/70 p-5 shadow-lg">
                <div className="flex items-center justify-between mb-2">
                  <span className={`text-xs font-medium px-2 py-1 rounded uppercase tracking-wider ${event.isSynthetic ? 'bg-purple-500/20 text-purple-300' : 'bg-blue-500/20 text-blue-300'}`}>
                    {event.isSynthetic ? 'Synthetic' : 'System'}
                  </span>
                  <time className="text-xs text-slate-500">{new Date(event.timestamp).toLocaleString()}</time>
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">{event.eventType}</h3>
                <div className="text-sm text-slate-400 space-y-1 bg-slate-950 p-3 rounded-xl border border-slate-800">
                  <p><span className="text-slate-500">User:</span> {event.user}</p>
                  <p><span className="text-slate-500">IP:</span> {event.ip} ({event.country})</p>
                  <p><span className="text-slate-500">Device:</span> {event.device}</p>
                  <p><span className="text-slate-500">Endpoint:</span> {event.endpoint}</p>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <span className={`text-xs font-medium px-2 py-1 rounded-full ${
                    event.severity === 'High' ? 'bg-red-500/10 text-red-300' : 'bg-slate-800 text-slate-300'
                  }`}>
                    Severity: {event.severity}
                  </span>
                  <span className="text-xs font-medium text-slate-400">Risk Score: {event.riskScore}</span>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </ProjectShell>
  );
}