import json
from sqlalchemy.orm import Session
from app.models.project import Project
from app.models.finding import Finding
from app.models.ai_summary import AISummary
from app.models.standard import StandardMapping
from app.schemas.ai_summary import AISummaryCreateRequest
import uuid

def generate_summary(db: Session, project_id: str, request: AISummaryCreateRequest) -> AISummary:
    # Get project
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise ValueError("Project not found")

    finding = None
    if request.finding_id:
        finding = db.query(Finding).filter(Finding.id == request.finding_id, Finding.project_id == project_id).first()
        if not finding:
            raise ValueError("Finding not found in this project")

    # Simple template based summary
    title = f"Investigation Summary for {project.name}"
    if finding:
        title += f" - {finding.title}"

    from app.models.scan import Scan
    scans = db.query(Scan).filter(Scan.project_id == project_id).order_by(Scan.created_at.desc()).all()
    
    # Default evidence list
    evidence_list = []
    if finding:
        evidence_list.append({"type": "finding_data", "details": f"Finding {finding.id} data analyzed."})
    else:
        evidence_list.append({"type": "project_data", "details": "All project findings and data analyzed."})
        if scans:
            evidence_list.append({"type": "scan_history", "details": f"Analyzed latest scan metrics (Score: {scans[0].posture_score})."})

    executive_summary = "Based on the evidence analyzed, this report summarizes the current security posture."
    what_happened = "An automated investigation scan was performed across the designated scope, revealing potential misconfigurations and areas requiring further monitoring."
    claim_status = "informational"
    confidence_explanation = "Low confidence due to reliance on static evidence and synthetic patterns without manual verification."
    impact_blast_radius = "Minimal direct impact observed, but unaddressed issues could increase attack surface."
    
    unknowns_and_limitations = "Investigation is limited to available log and configuration data. Actual exploitation cannot be confirmed."
    if len(scans) < 2:
        unknowns_and_limitations += " Before/after comparison unavailable because fewer than two scans were recorded."
        
    if finding and finding.rule_key:
        unknowns_and_limitations += f" Rule configuration for '{finding.rule_key}' may have changed after this finding was generated."
        evidence_list.append({"type": "detection_rule_context", "details": f"Analyzed finding generated by rule: {finding.rule_key}."})
        
        mapping = db.query(StandardMapping).filter(StandardMapping.finding_id == finding.id).first()
        if mapping:
            evidence_list.append({"type": "standard_mapping_context", "details": f"Finding aligns with {mapping.framework} {mapping.standard_version} - Control: {mapping.control_id}. ({mapping.mapping_reason})"})
        else:
            unknowns_and_limitations += " Standard mapping guidance is unavailable for this finding."
            
    safety_boundary = "This summary is defensive-only. No offensive payloads, credentials, exploit instructions, brute force steps, or authentication bypass guidance are generated. This report is for remediation and learning, not formal compliance certification."
    
    if finding:
        executive_summary = f"Analysis of finding {finding.title} indicates potential risks within the affected components."
        what_happened = f"Technical investigation of {finding.id} confirms the presence of indicators described in the finding context."
        if finding.severity in ["Critical", "High"]:
            claim_status = "suspected"
            confidence_explanation = "Medium confidence based on severity level and presence of multiple corresponding indicators."
            impact_blast_radius = "Significant potential blast radius affecting internal systems or data confidentiality if unmitigated."
    else:
        if len(scans) >= 2:
            latest = scans[0]
            previous = scans[1]
            if (latest.posture_score or 0) > (previous.posture_score or 0):
                executive_summary += f" The security posture has improved from {previous.posture_score} to {latest.posture_score}."

    remediation = [{"action": "Review finding details"}, {"action": "Implement recommended patches"}]

    new_summary = AISummary(
        id=f"ais-{uuid.uuid4().hex[:8]}",
        project_id=project_id,
        finding_id=request.finding_id,
        title=title,
        summary_type=request.summary_type,
        claim_status=claim_status,
        executive_summary=executive_summary,
        what_happened=what_happened,
        evidence_considered_json=json.dumps(evidence_list),
        confidence_explanation=confidence_explanation,
        impact_blast_radius=impact_blast_radius,
        recommended_remediation_json=json.dumps(remediation),
        unknowns_and_limitations=unknowns_and_limitations,
        safety_boundary=safety_boundary
    )
    
    db.add(new_summary)
    db.commit()
    db.refresh(new_summary)
    return new_summary
